// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

var data = [
  {
    title: "Work",
    timeframes: {
      daily: {
        current: 5,
        previous: 7
      },
      weekly: {
        current: 32,
        previous: 36
      },
      monthly: {
        current: 103,
        previous: 128
      }
    }
  },
  {
    title: "Play",
    timeframes: {
      daily: {
        current: 1,
        previous: 2
      },
      weekly: {
        current: 10,
        previous: 8
      },
      monthly: {
        current: 23,
        previous: 29
      }
    }
  },
  {
    title: "Study",
    timeframes: {
      daily: {
        current: 0,
        previous: 1
      },
      weekly: {
        current: 4,
        previous: 7
      },
      monthly: {
        current: 13,
        previous: 19
      }
    }
  },
  {
    title: "Exercise",
    timeframes: {
      daily: {
        current: 1,
        previous: 1
      },
      weekly: {
        current: 4,
        previous: 5
      },
      monthly: {
        current: 11,
        previous: 18
      }
    }
  },
  {
    title: "Social",
    timeframes: {
      daily: {
        current: 1,
        previous: 3
      },
      weekly: {
        current: 5,
        previous: 10
      },
      monthly: {
        current: 21,
        previous: 23
      }
    }
  },
  {
    title: "Self Care",
    timeframes: {
      daily: {
        current: 0,
        previous: 1
      },
      weekly: {
        current: 2,
        previous: 2
      },
      monthly: {
        current: 7,
        previous: 11
      }
    }
  }
];

function activityColor(activity) {
  switch (activity) {
    case "Exercise" :
        return "bg-color4";
    case "Play" :
        return "bg-color2";
    case "Self Care" :
        return "bg-color6";
    case "Social" :
        return "bg-color5";
    case "Study" :
        return "bg-color3";
    case "Work" :
        return "bg-color1";
    default:
      return "";
  }
}

function activityIcon(activity) {
  switch (activity) {
    case "Exercise" :
        return JsxRuntime.jsx("img", {
                    className: "absolute -top-2 right-3",
                    src: "/icon-exercise.svg"
                  });
    case "Play" :
        return JsxRuntime.jsx("img", {
                    className: "absolute -top-2 right-3",
                    src: "/icon-play.svg"
                  });
    case "Self Care" :
        return JsxRuntime.jsx("img", {
                    className: "absolute -top-2 right-3",
                    src: "/icon-self-care.svg"
                  });
    case "Social" :
        return JsxRuntime.jsx("img", {
                    className: "absolute -top-2 right-3",
                    src: "/icon-social.svg"
                  });
    case "Study" :
        return JsxRuntime.jsx("img", {
                    className: "absolute -top-2 right-3",
                    src: "/icon-study.svg"
                  });
    case "Work" :
        return JsxRuntime.jsx("img", {
                    className: "absolute -top-2 right-3",
                    src: "/icon-work.svg"
                  });
    default:
      return JsxRuntime.jsx(JsxRuntime.Fragment, {});
  }
}

export {
  data ,
  activityColor ,
  activityIcon ,
}
/* react/jsx-runtime Not a pure module */
