// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Cards from "../Components/Cards/Cards.bs.mjs";
import * as React from "react";
import * as Profile from "../Components/Profile.bs.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function App(props) {
  var match = React.useState(function () {
        return /* Daily */0;
      });
  var timesData = match[0];
  console.log(timesData);
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsxs("div", {
                    children: [
                      JsxRuntime.jsx(Profile.make, {
                            timeChanger: match[1]
                          }),
                      JsxRuntime.jsx(Cards.make, {
                            time: timesData
                          })
                    ],
                    className: "grid grid-cols-1 lg:grid-cols-3 items-center my-20 lg:my-auto gap-10"
                  }),
              className: "w-full h-full lg:h-screen bg-[#0D1323] flex justify-center lg:items-center font-custom p-10 lg:p-20"
            });
}

var make = App;

export {
  make ,
}
/* Cards Not a pure module */
